package com.gitub.eddboyer.launchpadrecruits.exceptions;

/**
 * Exception which may be best to notify the use about.
 * 
 * @author Edd Boyer
 */
public class NotifyUserException extends Exception {

	/**
	 * Generated by eclipse.
	 */
	private static final long serialVersionUID = -8220565154715241273L;

	/**
	 * @see Exception#Exception()
	 */
	public NotifyUserException() {
		super();
	}

	/**
	 * @see Exception#Exception(String, Throwable)
	 * @param message
	 *            The exception message.
	 * @param cause
	 *            The cause of this exception.
	 */
	public NotifyUserException(String message, Throwable cause) {
		super(message, cause);
	}

	/**
	 * @see Exception#Exception(String)
	 * @param message
	 *            The exception message.
	 */
	public NotifyUserException(String message) {
		super(message);
	}

	/**
	 * @see Exception#Exception(String, Throwable)
	 * @param cause
	 *            The cause of this exception.
	 */
	public NotifyUserException(Throwable cause) {
		super(cause);
	}
}
